Resolve timing-based CI failure
Browser tests periodically fail due to a timing issue:

```
1) [firefox] › functional/frame_tests.js:190:5 › failing to follow a link to a page without a matching frame shows an error and throws an exception

    AssertionError: expected 'Missing frame Missing page Unvisitabl…' to match /Content missing/

      196 |   await page.click("#missing-page-link")
      197 |
    > 198 |   assert.match(await page.innerText("#missing"), /Content missing/)
          |          ^
      199 |
      200 |   assert.exists(error)
      201 |   assert.include(error.message, `The response (404) did not contain the expected <turbo-frame id="missing">`)
```

This commit replaces the `assert`-based assertion with an `expect`-based
Playwright assertion that will utilize retries and timing
synchronization.

[CI failure]: https://github.com/hotwired/turbo/actions/runs/10603228414/job/29387060926?pr=1306#step:11:18