Resolve progress bar test suite failure (#535)
Merging [hotwired/turbo#501][] into `main` introduced a [consistent
failure to the test suite][ci-failure]:

```
× firefox on linux 5.11.0-1022-azure - RenderingTests - progress bar inline style has nonce (0.32s)
458
    AssertionError: displays progress bar: expected false to be truthy
459
      at RenderingTests.test progress bar inline style has nonce @ src/tests/functional/rendering_tests.ts:24:16
460
      at processTicksAndRejections @ internal/process/task_queues.js:97:5
461
      at async RenderingTests.runTest @ src/tests/helpers/intern_test_case.ts:43:6
```

This commit re-structures the test to make the same assertion (replacing
the [script][] tagname with [style][]).

[script]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
[style]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
[ci-failure]: https://github.com/hotwired/turbo/runs/4574673552?check_suite_focus=true#step:7:457
[hotwired/turbo#501]: https://github.com/hotwired/turbo/pull/501